Dependencies:
- 'on': ['Linux', 'FreeBSD', 'Windows', 'macOS']
  'require':
    'frameworks/extra-cmake-modules': '@same'
    'frameworks/ki18n' : '@same'
    'frameworks/karchive' : '@same'
    'frameworks/kcoreaddons' : '@same'
    'third-party/taglib' : '@same'
    'third-party/poppler' : '@same'

Options:
  test-before-installing: True
